apiVersion: v1
kind: ConfigMap
metadata:
  name: pyth-scheduler-price-config
  labels:
    app: pyth-scheduler
data:
  price-config.yaml: |
    - alias: SolvBTC/USD
      id: "0xf253cf87dc7d5ed5aa14cba5a6e79aee8bcfaef885a0e1b807035a0bbecc36fa"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: BTC/USD
      id: "0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43"
      time_difference: 600
      price_deviation: 0.5
      confidence_ratio: 75
    - alias: MUSD/USD
      id: "0x0617a9b725011a126a2b9fd53563f4236501f32cf76d877644b943394606c6de"
      time_difference: 600
      price_deviation: 0.1
      confidence_ratio: 75
    - alias: cbBTC/USD
      id: "0x2817d7bfe5c64b8ea956e9a26f573ef64e72e4d7891f2d6af9bcc93f7aff9a97"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: USDC/USD
      id: "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: USDT/USD
      id: "0x2b89b9dc8fdf9f34709a5b106b472f0f39bb6ca9ce04b0fd7f2e971688e2e53b"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: NVDA/USD
      id: "0xb1073854ed24cbc755dc527418f52b7d271f6cc967bbf8d8129112b18860a593"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: GOOGL/USD
      id: "0x5a48c03e9b9cb337801073ed9d166817473697efff0d138874e0f6a33d6d5aa6"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: TSLA/USD
      id: "0x16dad506d7db8da01c87581c87ca897a012a153557d4d578c3b9c9e1bc0632f1"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: MSTR/USD
      id: "0xe1e80251e5f5184f2195008382538e847fafc36f751896889dd3d1b1f6111f09"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: COIN/USD
      id: "0xfee33f2a978bf32dd6b662b65ba8083c6773b494f8401194ec1870c640860245"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
    - alias: CRCL/USD
      id: "0x92b8527aabe59ea2b12230f7b532769b133ffb118dfbd48ff676f14b273f1365"
      time_difference: 3600
      price_deviation: 1
      confidence_ratio: 75
